# frozen_string_literal: true

module Breadkit
  module Render
    class SvgRenderer
      PITCH = 10.0
      PALETTE = %w[#d62728 #1f77b4 #2ca02c #9467bd #ff7f0e #17becf].freeze

      def render(circuit, crop: "auto", theme: "light", show_nets: false, legend: false, color_by: "wire", annotations: [])
        @circuit, @theme, @show_nets, @color_by, @annotations = circuit, theme, show_nets, color_by, annotations
        @used_holes = circuit.nets.flat_map(&:holes).uniq
        @view_box = view_box(crop)
        left, top, width, height = @view_box
        svg = ["<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
               "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"#{fmt(width)}\" height=\"#{fmt(height)}\" viewBox=\"#{fmt(left)} #{fmt(top)} #{fmt(width)} #{fmt(height)}\" font-family=\"Helvetica, Arial, 'Noto Sans JP', sans-serif\" fill=\"#{@theme == 'dark' ? '#fff' : '#222'}\" role=\"img\">",
               "<title>#{escape(circuit.title || "Breadkit circuit")}</title>",
               "<desc>Breadboard wiring diagram generated by Breadkit.</desc>"]
        svg << "<g id=\"board\">#{board_svg}</g>"
        svg << "<g id=\"holes\">#{holes_svg}</g>"
        svg << "<g id=\"labels\">#{labels_svg}</g>"
        svg << "<g id=\"components\">#{components_svg}</g>"
        svg << "<g id=\"offboard\">#{offboard_svg}</g>"
        svg << "<g id=\"wires\">#{wires_svg}</g>"
        svg << "<g id=\"nets\">#{nets_svg}</g><g id=\"annotations\">#{annotations_svg}</g>"
        svg << "<g id=\"legend\">#{legend || !@annotations.empty? ? legend_svg : ""}</g></svg>"
        svg.join("\n")
      end

      private

      def board_svg
        color = { "dark" => "#263238", "print" => "#ffffff" }.fetch(@theme, "#dce9ce")
        out = [rect(-8, -36, (@circuit.board.width + 15) * PITCH, 170, rx: 12, fill: color, stroke: "#84917f")]
        out << rect(-5, py(4) - 4, (@circuit.board.width + 9) * PITCH, 8, fill: @theme == "dark" ? "#111820" : "#b8c6b4")
        @circuit.board.strips.each do |id, ids|
          next unless id.start_with?("rail:")
          holes = ids.map { |hole_id| @circuit.board.hole(hole_id) }
          next if holes.empty?
          rail = id.split(":")[1]
          rail_color = rail.end_with?("+") ? "#d34c49" : "#477fb5"
          out << line(px(holes.first.x), py(holes.first.y), px(holes.last.x), py(holes.last.y), rail_color, 2.4)
        end
        out.join
      end

      def holes_svg
        @circuit.board.holes.values.map do |hole|
          used = @used_holes.include?(hole.id)
          fill = used ? "#424b43" : (@theme == "dark" ? "#7c8780" : "#879381")
          circle(px(hole.x), py(hole.y), used ? 1.7 : 1.25,
                 fill: fill, data_hole: hole.id, opacity: used ? 1 : 0.68)
        end.join
      end

      def labels_svg
        out = []
        %w[a b c d e f g h i j].each do |row|
          y = @circuit.board.holes.values.find { |hole| hole.row == row }&.y
          out << text(-5, py(y), row, "font-size" => 4, "text-anchor" => "middle") if y
        end
        (1..@circuit.board.width).each do |col|
          out << text(px(col - 1), py(@circuit.board.height) + 8, col, "font-size" => 3.5, "text-anchor" => "middle")
        end
        out.join
      end

      def components_svg
        @circuit.components.values.map do |component|
          pins = component.pins.values.filter_map { |pin| [pin, @circuit.board.hole(pin.hole_id)] if pin.hole_id }
          next if pins.empty?
          xs, ys = pins.map { |_pin, hole| px(hole.x) }, pins.map { |_pin, hole| py(hole.y) }
          center_x, center_y = (xs.min + xs.max) / 2.0, (ys.min + ys.max) / 2.0
          shape = component.part.data.dig("render", "shape")
          body = case shape
          when "resistor" then resistor_svg(component, pins, center_x, center_y)
          when "led_5mm" then led_svg(component, pins, center_x, center_y)
          when "diode" then diode_svg(component, pins, center_x, center_y)
          when "capacitor", "electrolytic" then capacitor_svg(component, pins, center_x, center_y, electrolytic: shape == "electrolytic")
          when "dip" then dip_svg(component, pins)
          when "tact_switch" then switch_svg(component, pins, center_x, center_y)
          else generic_svg(component, pins, center_x, center_y)
          end
          "<g data-ref=\"#{escape(component.ref)}\">#{body}</g>"
        end.compact.join
      end

      def resistor_svg(component, pins, x, y)
        out = [lead_lines(pins, x, y)]
        out << rect(x - 12, y - 4, 24, 8, rx: 3, fill: "#f0d79c", stroke: "#654f36", data_ref: component.ref)
        resistor_bands(component.value).each_with_index { |color, index| out << rect(x - 7 + index * 4, y - 4, 1.7, 8, fill: color) }
        out << text(x, y - 7, "#{component.ref} #{component.value}", "font-size" => 4, "text-anchor" => "middle")
        out.join
      end

      def led_svg(component, pins, x, y)
        out = [lead_lines(pins, x, y)]
        color = { "red" => "#df5550", "green" => "#5fbf69", "blue" => "#6a9df0", "yellow" => "#f0d958" }.fetch(component.attrs[:color].to_s, "#df5550")
        out << circle(x, y, 5.5, fill: color, stroke: "#733b39", data_ref: component.ref)
        out << polarity_marker(component, pins, x, y, 5.0, "#733b39")
        out << text(x, y - 8, component.ref, "font-size" => 4, "text-anchor" => "middle")
        out.join
      end

      def diode_svg(component, pins, x, y)
        [lead_lines(pins, x, y), rect(x - 7, y - 3, 14, 6, rx: 1, fill: "#35383b", stroke: "#191b1d", data_ref: component.ref),
         polarity_marker(component, pins, x, y, 3.0, "#eee"),
         text(x, y - 5, component.ref, "font-size" => 3.5, "text-anchor" => "middle")].join
      end

      def capacitor_svg(component, pins, x, y, electrolytic:)
        out = [lead_lines(pins, x, y)]
        out << line(x - 2, y - 4, x - 2, y + 4, "#555", 1.1)
        out << line(x + 2, y - 4, x + 2, y + 4, "#555", 1.1)
        if electrolytic
          positive, negative = polarity_points(component, pins)
          offset_x = positive && negative && (positive[0] - negative[0]).abs < (positive[1] - negative[1]).abs ? 0 : (positive && positive[0] > x ? 5 : -5)
          offset_y = offset_x.zero? ? (positive && positive[1] > y ? 5 : -5) : 0
          out << text(x + offset_x, y + offset_y + 1.5, "+", "font-size" => 4, "text-anchor" => "middle")
        end
        out << text(x, y - 6, component.ref, "font-size" => 3.5, "text-anchor" => "middle")
        out.join
      end

      def dip_svg(component, pins)
        xs, ys = pins.map { |_pin, hole| px(hole.x) }, pins.map { |_pin, hole| py(hole.y) }
        x1, x2, middle = xs.min - 4, xs.max + 4, (ys.min + ys.max) / 2.0
        out = [rect(x1, middle - 4, x2 - x1, 8, rx: 2, fill: "#33393d", stroke: "#151719", data_ref: component.ref)]
        first_pin = pins.find { |pin, _hole| pin.number == "1" }&.last
        notch_x = first_pin && px(first_pin.x) > xs.sum / xs.length ? x2 - 2 : x1 + 2
        out << tag("path", d: "M #{fmt(notch_x)} #{fmt(middle - 2)} Q #{fmt(notch_x + (notch_x == x1 + 2 ? 2 : -2))} #{fmt(middle)} #{fmt(notch_x)} #{fmt(middle + 2)}",
                    fill: "none", stroke: "#aaa", stroke_width: 0.8)
        out << text((x1 + x2) / 2, middle + 1.5, component.part.data.dig("render", "label") || component.ref,
                    "font-size" => 3.5, "fill" => "white", "text-anchor" => "middle")
        pins.each do |pin, hole|
          out << text(px(hole.x), py(hole.y) + (hole.y > 4 ? 4 : -2), pin.number, "font-size" => 2.7, "text-anchor" => "middle")
        end
        out.join
      end

      def switch_svg(component, pins, x, y)
        out = [lead_lines(pins, x, y)]
        out << rect(x - 12, y - 10, 24, 20, rx: 2, fill: "#ece7dd", stroke: "#504c45", data_ref: component.ref)
        out << circle(x, y, 5, fill: "#c7c0b5", stroke: "#6c655b")
        out << text(x, y - 13, component.ref, "font-size" => 4, "text-anchor" => "middle")
        out.join
      end

      def generic_svg(component, pins, x, y)
        out = [lead_lines(pins, x, y)]
        out << rect(x - 9, y - 5, 18, 10, rx: 2, fill: "#faf8f3", stroke: "#555", data_ref: component.ref)
        out << text(x, y + 1.5, component.ref, "font-size" => 3.5, "text-anchor" => "middle")
        out.join
      end

      def offboard_svg
        @circuit.components.values.filter_map do |component|
          next unless component.part.placement == "offboard"
          pins = component.pins.values
          left = component.attrs[:side].to_s != "right"
          x = left ? -9.5 : @circuit.board.width + 2.5
          y = @circuit.board.height / 2.0
          width = 7.0
          height = [pins.length * 0.8 + 1.5, 4.0].max
          rect_x = left ? x - width : x
          out = [rect(px(rect_x), py(y + height / 2), px(width), px(height), rx: 2,
                      fill: @theme == "dark" ? "#37474f" : "#e9e4d8", stroke: "#57534b", data_ref: component.ref)]
          out << text(px(rect_x + width / 2), py(y + height / 2 - 0.5),
                      component.part.data.dig("render", "label") || component.ref,
                      "font-size" => 3.2, "text-anchor" => "middle")
          pins.each_with_index do |pin, index|
            pin_y = y + (index - (pins.length - 1) / 2.0) * 0.8
            pin_x = left ? x : x
            out << circle(px(pin_x), py(pin_y), 1.2, fill: "#5e6660", data_pin: "#{component.ref}.#{pin.name}")
            label_x = px(left ? rect_x + 0.4 : rect_x + width - 0.4)
            anchor = left ? "start" : "end"
            out << text(label_x, py(pin_y) + 1, pin.name, "font-size" => 2.5, "text-anchor" => anchor)
          end
          out.join
        end.join
      end

      def lead_lines(pins, x, y)
        pins.map { |_pin, hole| line(px(hole.x), py(hole.y), x, y, "#657067", 0.65) }.join
      end

      def polarity_points(component, pins)
        polarity = component.part.data["polarity"] || {}
        [polarity["positive"], polarity["negative"]].map do |name|
          pin, hole = pins.find { |candidate, _hole| candidate.name == name }
          [px(hole.x), py(hole.y)] if pin && hole
        end
      end

      def polarity_marker(component, pins, x, y, extent, color)
        positive, negative = polarity_points(component, pins)
        if positive && negative && (negative[0] - positive[0]).abs >= (negative[1] - positive[1]).abs
          marker_x = negative[0] > positive[0] ? x + extent / 2 : x - extent / 2
          line(marker_x, y - extent, marker_x, y + extent, color, 1.2)
        elsif positive && negative
          marker_y = negative[1] > positive[1] ? y + extent / 2 : y - extent / 2
          line(x - extent, marker_y, x + extent, marker_y, color, 1.2)
        else
          line(x - extent / 2, y - extent, x - extent / 2, y + extent, color, 1.2)
        end
      end

      def wires_svg
        @circuit.wires.map do |wire|
          from, to = endpoint_point(wire.from), endpoint_point(wire.to)
          next unless from && to
          color = @theme == "print" ? "#222222" : (wire.color || wire_color(wire))
          path = if wire.route == "arc"
            control_y = (py(from[1]) + py(to[1])) / 2.0 - 8
            "M #{fmt(px(from[0]))} #{fmt(py(from[1]))} Q #{fmt((px(from[0]) + px(to[0])) / 2)} #{fmt(control_y)} #{fmt(px(to[0]))} #{fmt(py(to[1]))}"
          else
            "M #{fmt(px(from[0]))} #{fmt(py(from[1]))} L #{fmt(px(to[0]))} #{fmt(py(to[1]))}"
          end
          dash = @theme == "print" ? " stroke-dasharray=\"#{["8 3", "3 3", "1 3"][@circuit.wires.index(wire).to_i % 3]}\"" : ""
          "<path d=\"#{path}\" fill=\"none\" stroke=\"#{escape(color)}\" stroke-width=\"6\" stroke-linecap=\"round\" data-ref=\"#{escape(wire.id)}\"#{dash}/>"
        end.compact.join
      end

      def nets_svg
        return "" unless @show_nets
        @circuit.nets.map do |net|
          hole = @circuit.board.hole(net.holes.first)
          next unless hole
          text(px(hole.x) + 4, py(hole.y) - 4, net.name, "font-size" => 4, "fill" => @theme == "dark" ? "#fff" : "#30363b", "data-net" => net.name)
        end.compact.join
      end

      def legend_svg
        out = [text(0, py(-4), @circuit.title || "Breadkit circuit", "font-size" => 6, "font-weight" => "bold")]
        @annotations.each_with_index do |item, index|
          message = read(item, "message") || read(item, "rule")
          out << text(0, py(-4) + 9 + index * 7, "#{index + 1}. #{message}", "font-size" => 3.5)
        end
        out.join
      end

      def annotations_svg
        @annotations.each_with_index.map do |item, index|
          targets = read(item, "targets") || {}
          severity = read(item, "severity")
          color = { "error" => "#d62728", "warning" => "#e67e22", "info" => "#2474c2" }.fetch(severity, "#d62728")
          out = []
          Array(read(targets, "holes")).each do |id|
            hole = @circuit.board.hole(id)
            out << circle(px(hole.x), py(hole.y), 4, fill: "none", stroke: color, stroke_width: 1.5) if hole
          end
          Array(read(targets, "wires")).each do |id|
            wire = @circuit.wires.find { |candidate| candidate.id == id }
            next unless wire
            point = endpoint_point(wire.from)
            out << circle(px(point[0]), py(point[1]), 5, fill: "none", stroke: color, stroke_width: 1.5) if point
          end
          Array(read(targets, "components")).each do |ref|
            component = @circuit.components[ref]
            holes = component && component.pins.values.map { |pin| @circuit.board.hole(pin.hole_id) }.compact
            next if holes.nil? || holes.empty?
            xs, ys = holes.map { |hole| px(hole.x) }, holes.map { |hole| py(hole.y) }
            out << rect(xs.min - 7, ys.min - 7, xs.max - xs.min + 14, ys.max - ys.min + 14,
                        fill: "none", stroke: color, stroke_width: 1.5)
          end
          out << text(@view_box ? @view_box[0] + 3 : 0, @view_box ? @view_box[1] + 10 + index * 7 : 10 + index * 7,
                      index + 1, "font-size" => 4, "font-weight" => "bold", "fill" => color)
          out.join
        end.join
      end

      def read(hash, key)
        hash[key] || hash[key.to_sym] if hash.respond_to?(:[])
      end

      def view_box(mode)
        offboard = @circuit.components.values.any? { |component| component.part.placement == "offboard" }
        if mode == "none" || (@used_holes.empty? && !offboard)
          return [offboard ? -PITCH * 11 : -PITCH, -PITCH * 3.5,
                  (@circuit.board.width + (offboard ? 13 : 2)) * PITCH, (@circuit.board.height + 6) * PITCH]
        end
        points = @used_holes.filter_map { |id| hole = @circuit.board.hole(id); [hole.x, hole.y] if hole }
        points.concat(@circuit.wires.flat_map { |wire| [endpoint_point(wire.from), endpoint_point(wire.to)] }.compact)
        points.concat(@circuit.components.values.select { |component| component.part.placement == "offboard" }
                              .flat_map { |component| offboard_bounds(component) })
        xs, ys = points.map { |x, _y| px(x) }, points.map { |_x, y| py(y) }
        return [-PITCH, -PITCH * 3.5, (@circuit.board.width + 2) * PITCH, (@circuit.board.height + 6) * PITCH] if xs.empty?
        [xs.min - 25, ys.min - 30, [xs.max - xs.min + 50, 100].max, [ys.max - ys.min + 65, 100].max]
      end

      def endpoint_point(endpoint)
        parsed = Breadkit::HoleId.parse(endpoint)
        if parsed.kind == :pin
          component = @circuit.components[parsed.ref]
          if component&.part&.placement == "offboard"
            pins = component.pins.values
            pin = pins.find { |item| item.name == parsed.pin || item.number == parsed.pin }
            return unless pin
            index = pins.index(pin)
            x = component.attrs[:side].to_s == "right" ? @circuit.board.width + 2.5 : -9.5
            y = @circuit.board.height / 2.0 + (index - (pins.length - 1) / 2.0) * 0.8
            return [x, y]
          end
        end
        hole = @circuit.board.hole(endpoint)
        [hole.x, hole.y] if hole
      rescue ArgumentError
        nil
      end

      def offboard_bounds(component)
        left = component.attrs[:side].to_s != "right"
        x = left ? -9.5 : @circuit.board.width + 2.5
        height = [component.pins.length * 0.8 + 1.5, 4.0].max
        center = @circuit.board.height / 2.0
        [[left ? x - 7 : x, center - height / 2], [left ? x : x + 7, center + height / 2]]
      end

      def wire_color(wire)
        if @color_by == "net"
          hole = @circuit.board.hole(wire.from)
          net = @circuit.nets.find { |item| item.members.include?(wire.id) } ||
                (hole && @circuit.nets.find { |item| item.holes.include?(hole.id) })
          voltage = net && @circuit.potentials.values[net.name]
          return voltage.to_f.positive? ? "#d33b36" : "#222222" if voltage
          if net
            hash = net.name.each_byte.reduce(2_166_136_261) { |value, byte| ((value ^ byte) * 16_777_619) & 0xffffffff }
            return "#%06x" % (hash & 0xffffff)
          end
        end
        PALETTE[@circuit.wires.index(wire).to_i % PALETTE.length]
      end

      def resistor_bands(value)
        number = Breadkit::Value.parse(value || 0)
        return %w[#a0522d #a0522d #a0522d #d4af37] if number <= 0
        exponent = Math.log10(number).floor - 1
        digits = (number / (10.0**exponent)).round
        colors = %w[#000000 #8b4513 #ff0000 #ff8c00 #ffff00 #008000 #0000ff #800080 #808080 #ffffff]
        [colors[(digits / 10) % 10], colors[digits % 10], colors[[exponent, 0].max % 10], "#d4af37"]
      rescue ArgumentError
        %w[#a0522d #a0522d #a0522d #d4af37]
      end

      def px(x)
        x.to_f * PITCH
      end

      def py(y)
        (@circuit.board.height - 1 - y.to_f) * PITCH
      end

      def fmt(value)
        format("%.2f", value.to_f)
      end

      def escape(value)
        CGI.escapeHTML(value.to_s)
      end

      def tag(name, attrs = nil, **options)
        attrs = (attrs || {}).merge(options)
        attributes = attrs.map { |key, value| "#{key.to_s.tr('_', '-')}=\"#{escape(value)}\"" }.join(" ")
        "<#{name} #{attributes}/>"
      end

      def rect(x, y, width, height, **attrs)
        tag("rect", { x: fmt(x), y: fmt(y), width: fmt(width), height: fmt(height) }.merge(attrs))
      end

      def circle(x, y, radius, **attrs)
        tag("circle", { cx: fmt(x), cy: fmt(y), r: fmt(radius) }.merge(attrs))
      end

      def line(x1, y1, x2, y2, color, width)
        tag("line", x1: fmt(x1), y1: fmt(y1), x2: fmt(x2), y2: fmt(y2), stroke: color, stroke_width: fmt(width))
      end

      def text(x, y, value, attrs = {})
        attributes = { x: fmt(x), y: fmt(y) }.merge(attrs).map { |key, item| "#{key.to_s.tr('_', '-')}=\"#{escape(item)}\"" }.join(" ")
        "<text #{attributes}>#{escape(value)}</text>"
      end
    end
  end
end
